image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      cabal update
      stack build

    command: |
      stack test

vscode:
  extensions:
    - haskell.haskell

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true