image:
  file: .gitpod.Dockerfile
tasks:
  - init: >
      mkdir -p /home/gitpod/.config/nix &&
      echo 'sandbox = false' >> /home/gitpod/.config/nix/nix.conf &&
      stack build
  - command:
      python3 -m http.server 8080
  
vscode:
  extensions:
    - bbenoist.Nix
    - haskell.haskell
    - cab404.vscode-direnv
    - arrterian.nix-env-selector
